FORMAT: 1A
HOST: http://www.informaticacloud.com

# Informatica Cloud REST API
The Informatica Cloud REST API allows you to access information from your _Informatica Cloud_ organization. You can perform tasks such as create, update, and delete connections, schedules, mapplets, and task flows.arions.

# Group Session Management


##  Login [/login]
### Login to Informatica Cloud [POST]
Enter Valid username and password to access.

+ Parameters
    + username (required, string, `user@informaticacloud.com`) ... Informatica Cloud username
    + password (required, string, `password`) ... Informatica Cloud password
    


+ Request (application/json)

        {"@type":"login","username":"user@informatica.com","password":"password"}


+ Response 201 (application/json)

        {
          "@type" : "user",
          "id" : "000NJY03000000000002",
          "orgId" : "FFFFFF",
          "name" : "user@informatica.com",
          "description" : null,
          "createTime" : "2013-07-08T18:01:54.000Z",
          "updateTime" : "2014-02-25T15:46:34.000Z",
          "createdBy" : "System",
          "updatedBy" : "nbrisoux@informatica.com",
          "sfUsername" : null,
          "firstName" : "Name",
          "lastName" : "Surname",
          "title" : "Senior Cloud Platform Specialist",
          "password" : "**********",
          "phone" : "1231231234",
          "emails" : null,
          "timezone" : "America/Los_Angeles",
          "serverUrl" : "https://app2.informaticacloud.com/saas",
          "icSessionId" : "iEpnAXaIXfEhl6eO",
          "securityQuestion" : "SPOUSE_MEETING_CITY",
          "securityAnswer" : null,
          "roles" : [ {
            "@type" : "role",
            "id" : "001000000000003",
            "orgId" : "0",
            "name" : "Admin",
            "description" : "Role that has ability to perform administrative tasks for an organization.",
            "createTime" : "2013-05-24T16:30:32.000Z",
            "updateTime" : "2014-02-22T19:22:08.000Z",
            "createdBy" : "System",
            "updatedBy" : "System"
          } ],
          "usergroups" : [ ]
        }


## Logout [/logout]


### Logout of Informatica Cloud [POST]
Use this call to terminate an active Informatica Cloud session. You must provide the _icSessionId_ in the request header.

+ Request 

    + Header

            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            charset : "UTF-8"
            Content-type : "application/json"

    
+ Response 200

# Group Monitoring 

## Activity Log [/activityLog?rowLimit=<row limit>]


### Get a list of tasks that have completed [GET]

Returns an activityLogEntry object for each row in the activity log. Default behaviour is to return all rows but you can optionally supply a row limit.

+ Parameters
    + rowLimit (optional, integer, `3`) ... Informatica Cloud username
    
+ Request 

    + Header

            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            charset : "UTF-8"
            Content-type : "application/json"

    
+ Response 200 (application/json)   

        [ {
          "@type" : "activityLogEntry",
          "id" : "000NJYC100000000038R",
          "type" : "DSS",
          "objectName" : "strevus matching - filtered",
          "runId" : 2,
          "startTime" : "2014-03-06T17:25:49.000Z",
          "endTime" : "2014-03-06T17:25:53.000Z",
          "state" : 1,
          "failedSourceRows" : 0,
          "successSourceRows" : 12,
          "failedTargetRows" : 0,
          "successTargetRows" : 12,
          "errorMsg" : null,
          "entries" : [ {
            "@type" : "activityLogEntry",
            "id" : "8087583",
            "type" : "DSS",
            "objectName" : "FILTETRED_MATCHEDCOMPANIES",
            "runId" : 0,
            "startTime" : "2014-03-06T17:25:49.000Z",
            "endTime" : "2014-03-06T17:25:53.000Z",
            "state" : 1,
            "failedSourceRows" : 0,
            "successSourceRows" : 12,
            "failedTargetRows" : 0,
            "successTargetRows" : 12,
            "errorMsg" : "No errors encountered.",
            "entries" : [ ]
          } ]
        },  {
          "@type" : "activityLogEntry",
          "id" : "000NJYC10000000003EB",
          "type" : "DRS",
          "objectName" : "strevus matching copy",
          "runId" : 1,
          "startTime" : "2014-03-06T17:23:27.000Z",
          "endTime" : "2014-03-06T17:23:35.000Z",
          "state" : 1,
          "failedSourceRows" : 0,
          "successSourceRows" : 99,
          "failedTargetRows" : 0,
          "successTargetRows" : 99,
          "errorMsg" : null,
          "entries" : [ {
            "@type" : "activityLogEntry",
            "id" : "8087455",
            "type" : "DRS",
            "objectName" : "matchedcompanies",
            "runId" : 0,
            "startTime" : "2014-03-06T17:23:31.000Z",
            "endTime" : "2014-03-06T17:23:35.000Z",
            "state" : 1,
            "failedSourceRows" : 0,
            "successSourceRows" : 99,
            "failedTargetRows" : 0,
            "successTargetRows" : 99,
            "errorMsg" : "No errors encountered.",
            "entries" : [ ]
          } ]
        },  {
          "@type" : "activityLogEntry",
          "id" : "000NJYC10000000002XL",
          "type" : "MTT_TEST",
          "objectName" : "advw2012toRedshift",
          "runId" : 1,
          "startTime" : "2014-02-28T14:04:22.000Z",
          "endTime" : "2014-02-28T14:04:40.000Z",
          "state" : 1,
          "failedSourceRows" : 0,
          "successSourceRows" : 19614,
          "failedTargetRows" : 0,
          "successTargetRows" : 19614,
          "errorMsg" : null,
          "entries" : [ {
            "@type" : "activityLogEntry",
            "id" : "7386788",
            "type" : "MTT_TEST",
            "objectName" : "",
            "runId" : 0,
            "startTime" : "2014-02-28T14:04:22.000Z",
            "endTime" : "2014-02-28T14:04:40.000Z",
            "state" : 1,
            "failedSourceRows" : 0,
            "successSourceRows" : 19614,
            "failedTargetRows" : 0,
            "successTargetRows" : 19614,
            "errorMsg" : "No errors encountered.",
            "entries" : [ ]
          } ]
        
# Group Activity Monitor 

## activityMonitor  [/activityMonitor?details=true]

### Use this resource to request information from the activity monitor [GET]

True : Returns activity monitor information for tasks, task flows, and child objects. Child objects can include tasks within task flows, and objects within data replication tasks and D&B360 workflows.

False :  Returns activity monitor information for tasks and task flows.

Default is false. 

+ Parameters
    + details (optional,boolean) ... true/false
    
+ Request 

    + Header
    
            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            Content-Type: "application/xml"
            Accept: "application/xml"
            
 
+ Response 200 (application/xml)
    
        <root> 
            <activityMonitorEntry> 
                <id>000001C100000000000D</id> 
                <type>DSS</type> 
                <objectName>dss-f2f</objectName> 
                <runId>0</runId> 
                <startTime>2012-07-30T13:30:00.000Z</startTime> 
                <endTime></endTime> 
                <executionState>RUNNING</executionState> 
                <failedSourceRows>0</failedSourceRows> 
                <successSourcerows>938</successSourceRows> 
                <failedTargetRows>0</failedTargetRows> 
                <successTargetRows>596</successTargetRows> 
                <errorMsg> </errorMsg> 
                <entries> </entries> 
            </activityMonitorEntry> 
            <activityMonitorEntry> 
                <id>000001C500000000000L</id> 
                <type>PCS</type> 
                <objectName>pcs-lookup</objectName> 
                <runId>2</runId> 
                <startTime>2012-07-30T13:30:03.001Z</startTime> 
                <endTime>2012-07-30T13:30:03.010Z</endTime> 
                <executionState>COMPLETE</executionState> 
                <failedSourceRows>0</failedSourceRows> 
                <successSourcerows>688</successSourceRows> 
                <failedTargetRows>0</failedTargetRows> 
                <successTargetRows>688</successTargetRows> 
                <errorMsg> </errorMsg> 
                <entries> </entries> 
            </activityMonitorEntry>
        </root>

# Group Agent

## agent [/agent/000IL10800000000000L]

### Details of an Informatica Cloud Secure Agent or the details of all Secure Agents in the organization [GET]
Use this resource to request the details of an Informatica Cloud Secure Agent or the details of all Secure Agents in the organization.

+ Request 

    + Header
    
            Accept:"application/json"
            icSessionId: "EFelWYBP4WmMeO2g9PJs" 
            
+ Response 200 (application/json)

        [ {
          "@type" : "id",
          "orgId" : "Org000IL1",
          "name" : "Secure Agent Name",
          "createTime" : "2",
          "updateTime" : "2015-03-27T10:16:37.000Z",
          "createdBy" : "admin",
          "updatedBy" : "admin",
          "active" : "true",
          "platform" : "Windows",
          "agentHost" : "INW00001769",
          "password" : "*********",
          "proxyHost" : "HostName",
          "proxyPort" : "portNumber",
          "proxyUser" : "userName",
          "proxyPassword" : "*******",
          "agentVersion" : "19.10.23.49.0.1.0",
          "upgradeStatus" : "Up-to-date",
          "lastUpgraded" : "2014-12-29T17:19:59.000Z",
          "lastUpgradeCheck" : "2014-12-29T17:19:59.000Z",
          "lastStatusChange" : "2014-12-29T17:19:59.000Z",
          "packages" : "Connectorpackages",
          "agentConfigs" : [ {
            "name" : "configPropertyName",
            "type" : "Secure Agent Core",
            "subType" : "INFO",
            "value" : 0,
            "customized" : "true",
            "overridden" : "true",
            "defaultValue" : 1,
            "platform" : "win32",
           } ],
          "configUpdateTime:"2015-01-2T12:02:21.000Z" 
         } ]

## Delete Request [/agent/id]

### To delete a Secure Agent, use the Secure Agent ID [DELETE]
You can delete a Secure Agent if it is not associated with any connections. Before you delete a Secure Agent, update associated connections to use another Secure Agent.


+ Response 200




        