FORMAT: 1A
HOST: http://www.informaticacloud.com

# Informatica Cloud REST API
The Informatica Cloud REST API allows you to access information from your _Informatica Cloud_ organization. You can perform tasks such as create, update, and delete connections, schedules, mapplets, and task flows.arions.

# Group Session Management


##  Login [/ma/api/v2/user/login]
### Login to Informatica Cloud [POST]
Enter Valid username and password to access.

+ Parameters
    + username (required, string, `user@informaticacloud.com`) ... Informatica Cloud username
     + password (required, string, `password`) ... Informatica Cloud password
     

+ Request (application/json)

        {
        "@type":"login",
        "username":"user@informatica.com",
        "password":"password"
        }


+ Response 201 (application/json)

        {
          "@type" : "user",
          "id" : "000NJY03000000000002",
          "orgId" : "FFFFFF",
          "name" : "user@informatica.com",
          "description" : null,
          "createTime" : "2013-07-08T18:01:54.000Z",
          "updateTime" : "2014-02-25T15:46:34.000Z",
          "createdBy" : "System",
          "updatedBy" : "nbrisoux@informatica.com",
          "sfUsername" : null,
          "firstName" : "Name",
          "lastName" : "Surname",
          "title" : "Senior Cloud Platform Specialist",
          "password" : "**********",
          "phone" : "1231231234",
          "emails" : null,
          "timezone" : "America/Los_Angeles",
          "serverUrl" : "https://app2.informaticacloud.com/saas",
          "icSessionId" : "iEpnAXaIXfEhl6eO",
          "securityQuestion" : "SPOUSE_MEETING_CITY",
          "securityAnswer" : null,
          "roles" : [ {
            "@type" : "role",
            "id" : "001000000000003",
            "orgId" : "0",
            "name" : "Admin",
            "description" : "Role that has ability to perform administrative tasks for an organization.",
            "createTime" : "2013-05-24T16:30:32.000Z",
            "updateTime" : "2014-02-22T19:22:08.000Z",
            "createdBy" : "System",
            "updatedBy" : "System"
          } ],
          "usergroups" : [ ]
        }


## Logout [/logout]


### Logout of Informatica Cloud [POST]
Use this call to terminate an active Informatica Cloud session. You must provide the _icSessionId_ in the request header.

+ Request 

    + Header

            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            charset : "UTF-8"
            Content-type : "application/json"

    
+ Response 200

# Group Monitoring 

## Activity Log [/activityLog?rowLimit=<row limit>]


### Get a list of tasks that have completed [GET]

Returns an activityLogEntry object for each row in the activity log. Default behaviour is to return all rows but you can optionally supply a row limit.

+ Parameters
    + rowLimit (optional, integer, `3`) ... Informatica Cloud username
    
+ Request 

    + Header

            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            charset : "UTF-8"
            Content-type : application/json"

    
+ Response 200 (application/json)   

        [ {
          "@type" : "activityLogEntry",
          "id" : "000NJYC100000000038R",
          "type" : "DSS",
          "objectName" : "strevus matching - filtered",
          "runId" : 2,
          "startTime" : "2014-03-06T17:25:49.000Z",
          "endTime" : "2014-03-06T17:25:53.000Z",
          "state" : 1,
          "failedSourceRows" : 0,
          "successSourceRows" : 12,
          "failedTargetRows" : 0,
          "successTargetRows" : 12,
          "errorMsg" : null,
          "entries" : [ {
            "@type" : "activityLogEntry",
            "id" : "8087583",
            "type" : "DSS",
            "objectName" : "FILTETRED_MATCHEDCOMPANIES",
            "runId" : 0,
            "startTime" : "2014-03-06T17:25:49.000Z",
            "endTime" : "2014-03-06T17:25:53.000Z",
            "state" : 1,
            "failedSourceRows" : 0,
            "successSourceRows" : 12,
            "failedTargetRows" : 0,
            "successTargetRows" : 12,
            "errorMsg" : "No errors encountered.",
            "entries" : [ ]
          } ]
        },  {
          "@type" : "activityLogEntry",
          "id" : "000NJYC10000000003EB",
          "type" : "DRS",
          "objectName" : "strevus matching copy",
          "runId" : 1,
          "startTime" : "2014-03-06T17:23:27.000Z",
          "endTime" : "2014-03-06T17:23:35.000Z",
          "state" : 1,
          "failedSourceRows" : 0,
          "successSourceRows" : 99,
          "failedTargetRows" : 0,
          "successTargetRows" : 99,
          "errorMsg" : null,
          "entries" : [ {
            "@type" : "activityLogEntry",
            "id" : "8087455",
            "type" : "DRS",
            "objectName" : "matchedcompanies",
            "runId" : 0,
            "startTime" : "2014-03-06T17:23:31.000Z",
            "endTime" : "2014-03-06T17:23:35.000Z",
            "state" : 1,
            "failedSourceRows" : 0,
            "successSourceRows" : 99,
            "failedTargetRows" : 0,
            "successTargetRows" : 99,
            "errorMsg" : "No errors encountered.",
            "entries" : [ ]
          } ]
        },  {
          "@type" : "activityLogEntry",
          "id" : "000NJYC10000000002XL",
          "type" : "MTT_TEST",
          "objectName" : "advw2012toRedshift",
          "runId" : 1,
          "startTime" : "2014-02-28T14:04:22.000Z",
          "endTime" : "2014-02-28T14:04:40.000Z",
          "state" : 1,
          "failedSourceRows" : 0,
          "successSourceRows" : 19614,
          "failedTargetRows" : 0,
          "successTargetRows" : 19614,
          "errorMsg" : null,
          "entries" : [ {
            "@type" : "activityLogEntry",
            "id" : "7386788",
            "type" : "MTT_TEST",
            "objectName" : "",
            "runId" : 0,
            "startTime" : "2014-02-28T14:04:22.000Z",
            "endTime" : "2014-02-28T14:04:40.000Z",
            "state" : 1,
            "failedSourceRows" : 0,
            "successSourceRows" : 19614,
            "failedTargetRows" : 0,
            "successTargetRows" : 19614,
            "errorMsg" : "No errors encountered.",
            "entries" : [ ]
          } ]
        
# Group Activity Monitor 

## activityMonitor  [/activityMonitor?details=true]

### Use this resource to request information from the activity monitor [GET]

True : Returns activity monitor information for tasks, task flows, and child objects. Child objects can include tasks within task flows, and objects within data replication tasks and D&B360 workflows.

False :  Returns activity monitor information for tasks and task flows.

Default is false. 

+ Parameters
    + details (optional,boolean) ... true/false
    
+ Request 

    + Header
    
            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            Content-Type: "application/json"
            Accept: "application/json"
            
 
+ Response 200 (application/xml)
    
        <root> 
            <activityMonitorEntry> 
                <id>000001C100000000000D</id> 
                <type>DSS</type> 
                <objectName>dss-f2f</objectName> 
                <runId>0</runId> 
                <startTime>2012-07-30T13:30:00.000Z</startTime> 
                <endTime></endTime> 
                <executionState>RUNNING</executionState> 
                <failedSourceRows>0</failedSourceRows> 
                <successSourcerows>938</successSourceRows> 
                <failedTargetRows>0</failedTargetRows> 
                <successTargetRows>596</successTargetRows> 
                <errorMsg> </errorMsg> 
                <entries> </entries> 
            </activityMonitorEntry> 
            <activityMonitorEntry> 
                <id>000001C500000000000L</id> 
                <type>PCS</type> 
                <objectName>pcs-lookup</objectName> 
                <runId>2</runId> 
                <startTime>2012-07-30T13:30:03.001Z</startTime> 
                <endTime>2012-07-30T13:30:03.010Z</endTime> 
                <executionState>COMPLETE</executionState> 
                <failedSourceRows>0</failedSourceRows> 
                <successSourcerows>688</successSourceRows> 
                <failedTargetRows>0</failedTargetRows> 
                <successTargetRows>688</successTargetRows> 
                <errorMsg> </errorMsg> 
                <entries> </entries> 
            </activityMonitorEntry>
        </root>

# Group Agent

## agent [/agent/id]

### Details of an Informatica Cloud Secure Agent or the details of all Secure Agents in the organization [GET]
Use this resource to request the details of an Informatica Cloud Secure Agent .To request the details of all Secure Agents in the organization, omit the optional Secure Agent ID.

+ Parameters
    + id (optional,string, `000IL10800000000000L`) ... required in case of to get details of particular Secure Agent. Optional in case of to get details of all Secure Agents.

+ Request 

    + Header
    
            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            Content-Type: "application/json"
            Accept: "application/json"
            
+ Response 200 (application/json)

        [ {
          "@type" : "agent",
          "orgId" : "Org000IL1",
          "name" : "Secure Agent Name",
          "createTime" : "2",
          "updateTime" : "2015-03-27T10:16:37.000Z",
          "createdBy" : "admin",
          "updatedBy" : "admin",
          "active" : "true",
          "platform" : "Windows",
          "agentHost" : "INW00001769",
          "password" : "*********",
          "proxyHost" : "HostName",
          "proxyPort" : "portNumber",
          "proxyUser" : "userName",
          "proxyPassword" : "*******",
          "agentVersion" : "19.10.23.49.0.1.0",
          "upgradeStatus" : "Up-to-date",
          "lastUpgraded" : "2014-12-29T17:19:59.000Z",
          "lastUpgradeCheck" : "2014-12-29T17:19:59.000Z",
          "lastStatusChange" : "2014-12-29T17:19:59.000Z",
          "packages" : "Connectorpackages",
          "agentConfigs" : [ {
            "name" : "configPropertyName",
            "type" : "Secure Agent Core",
            "subType" : "INFO",
            "value" : 0,
            "customized" : "true",
            "overridden" : "true",
            "defaultValue" : 1,
            "platform" : "win32",
           } ],
          "configUpdateTime:"2015-01-2T12:02:21.000Z" 
         } ]

## Delete Request [/agent/<id>]

### To delete a Secure Agent, use the Secure Agent ID [DELETE]
You can delete a Secure Agent if it is not associated with any connections. Before you delete a Secure Agent, update associated connections to use another Secure Agent.


+ Response 200 

# Group AuditLog

## auditlog [/auditlog?batchId=<batchId>&batchSize=<batchSize>]

### Use this resource to request entries from the audit log [GET]
To request the most recent 200 entries in the audit log.To request a specific batch of audit log entries, define the batch size and request a batch number.

+ Parameters
    + batchId (required, integer, `1` ) ... Batch ID
    + batchSize (required, integer, `25` ) ... Batch Size
        
+ Request 
    
    + Header
    
            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            Content-Type: "application/json"
            Accept: "application/json"
    
+ Response 200 (application/json)
            
            {
            "@type" : "auditlog",
            "id" :"000IL10300000000000L",
            "version":"r21",
            "orgId" : "Org000IL1",
            "username" : "user@informatica.com",
            "entryTime" : "2013-07-08T18:01:54.000Z",
            "objectId" : "000IL117000000000015",
            "objectName" : "Anush_MultiTarget",
            "category": "DSS Data synchronization",
            "event" : "UPDATE",
            "eventParam" : "Objects related to action",
            "message" : "additional information",
            }

    
# Group LogoutALL

## logoutall [/logoutall]

###Use this resource to log out of an organization and end all REST API sessions for the user in the request [POST]
Enter Valid username and password to access.

+ Parameters
    + username (required, string, `user@informaticacloud.com`) ... Informatica Cloud username
    + password (required, string, `password`) ... Informatica Cloud password
    
+ Request (application/json)

        {"@type":"login","username":"user@informatica.com","password":"password"}


+ Response 200

# Group User

## user [/user/<id>]

###Use this resource to request the details of an Informatica Cloud user account or the details of all user accounts in the organization [GET]

+ Parameters
    + id (required, string, `000IL10300000000000L`) ... required in case of to get details of particular user. Optional in case of to get details of all users.

+ Request

    + Header
    
            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            Content-Type: "application/json"
            Accept: "application/json"
        
+ Response 200 (application/json)

        {
          "@type" : "user",
          "id" : "000NJY03000000000002",
          "orgId" : "FFFFFF",
          "name" : "user@informatica.com",
          "description" : null,
          "createTime" : "2013-07-08T18:01:54.000Z",
          "updateTime" : "2014-02-25T15:46:34.000Z",
          "createdBy" : "System",
          "updatedBy" : "nbrisoux@informatica.com",
          "sfUsername" : null,
          "firstName" : "Name",
          "lastName" : "Surname",
          "title" : "Senior Cloud Platform Specialist",
          "password" : "**********",
          "phone" : "1231231234",
          "emails" : null,
          "timezone" : "America/Los_Angeles",
          "serverUrl" : "https://app2.informaticacloud.com/saas",
          "icSessionId" : "iEpnAXaIXfEhl6eO",
          "securityQuestion" : "SPOUSE_MEETING_CITY",
          "securityAnswer" : null,
          "roles" : [ {
            "@type" : "role",
            "id" : "001000000000003",
            "orgId" : "0",
            "name" : "Admin",
            "description" : "Role that has ability to perform administrative tasks for an organization.",
            "createTime" : "2013-05-24T16:30:32.000Z",
            "updateTime" : "2014-02-22T19:22:08.000Z",
            "createdBy" : "System",
            "updatedBy" : "System"
          } ],
          "usergroups" : [ {
            "@type" : "usergroups",
            "id" : "001000000000003",
            "orgId" : "0",
            "name" : "Admin",
            "description" : "Role that has ability to perform administrative tasks for an organization.",
            "createTime" : "2013-05-24T16:30:32.000Z",
            "updateTime" : "2014-02-22T19:22:08.000Z",
            "createdBy" : "System",
            "updatedBy" : "System",
            "aclEntry"   : "Permissions"
          } ],
          "emails" : "user@informatica.com",
          "timeZone" : "America/New_York",
          "serverUrl" : "https://app.informaticaondemand.com/saas/app/admin/users.do",
          "spiUrl" : "https://app.informaticaondemand.com/saas/app/admin/users.do",
          "icSessionId" : "EFelWYBP4WmMeO2g9PJs"
        }
    
# Group UserGroup

## usergroup [/usergroup/<id>]

### Use this resource to request the details of a user group or the details of all user groups in the organization [GET]
To request the details of a user group, use the user group ID . To request the details of all user groups in the organization, omit the optional ID.

+ Parameters
    + id (optional,string, `000IL105000000000003`) ... required in case of to get details of particular user group. Optional in case of to get details of all user groups.

+ Request 
        
    + Header
    
            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            Content-Type: "application/json"
            Accept: "application/json"
        
+ Response 200(application/json)
        
        {
          "@type" : "usergroup",
          "id" : "000NJY03000000000002",
          "orgId" : "FFFFFF",
          "name" : "user@informatica.com",
          "description" : null,
          "createTime" : "2013-07-08T18:01:54.000Z",
          "updateTime" : "2014-02-25T15:46:34.000Z",
          "createdBy" : "System",
          "updatedBy" : "nbrisoux@informatica.com",
          "aclEntry" : [ {
            "@type" : "aclEntry",
            "adminPermission" : "Permission for individual Objects",
            "createPermission" : "Allows to create objects",
            "deletePermission" : "delete objects",
            "executePermission" : "run task and task flows",
            "objectType" : "Agent",
            "readPermission" : "view object and project",
            "updatePermission" : "edit objects",
          } ]
        }

# Group Org

## org [/org/<id>]

### Use this resource to request the details of your Informatica Cloud organization or a related sub-organization.use this resource to update an organization or related sub-organization and also delete a sub-organization [GET]
To request the details of a sub-organization related to your organization, use the sub-organization ID.To request the details of your organization, omit the optional sub-organization ID.

+ Parameters
    + id (required,string, `Org000Y8D`) ... required in case of to get details of particular organization. Optional in case of to get details of organization.

+ Request  

    + Header
    
            icSessionId:"EFelWYBP4WmMeO2g9PJs"
            Content-Type: "application/json"
            Accept: "application/json"  

+ Response 200 (application/json)

        {
        "@type" : "user",
          "id" : "Org000Y8D",
          "orgId" : "Org000IL1",
          "name" : "Informatica",
          "description" : null,
          "createTime" : "2013-07-08T18:01:54.000Z",
          "updateTime" : "2014-02-25T15:46:34.000Z",
          "createdBy" : "System",
          "updatedBy" : "nbrisoux@informatica.com",
          "parentOrgId" : "Org000IL1",
          "address1" : "No. 66/1, Bagmane Commerz 02, Bagmane Tech Park",
          "address2" : "null",
          "address3" : "null",
          "city" : "Bangalore",
          "State" : "Karnataka",
          "zipcode" : "560093"
          "country" : "India",
          "employees" : "1000-5000",
          "offerCode" : null,
          "successEmails" : null,
          "warningEmails" : null,
          "errorEmails" : null,
          "campaignCode" : null,
          "atlasProjectId" : null,
          "zuoraAccountId" : null,
          "devOrg" : 1,
          "timezone" : "IndianStandard Time Delhi Bombay",
          "maxLogRows" : 100,
          "minPasswordLength" : 6,
          "minPasswordCharMix" : 1,
          "passwordReuseInDays" : 0,
          "passwordExpirationInDays" : 0,
          "subOrgLimit" : 2,
          "parentOrgId" : "Org000IL1",
          "jobExecUserProfile" : null,
          "twoFactorAuthentication" : "Disabled ",
          "ipAddressRanges" : "IPV4",
          "subOrg" : [ {
            "@type" : "subOrg",
            "id" : "Org000Y8D",
            "name" : "Marketplace_Bundle",
          } ],
        }
        
## UpdateOrg [/org/<orgID>]

### Use this resource to update a sub-organization if your organization has the Org Hierarchy license and if the user that started the REST API session has the Admin role in the parent organization [POST]
To update the details of a sub-organization related to your parent organization, use the organization ID.To update the details of your organization, omit the optional ID.

+ Parameters
    + orgID (required, string, `Org000IL1`) ... Organization ID
    
+ Request 
        
            <org> 
                <name>Dev Org</name> 
                <address1>333 Main Street</address1> 
                <city>City</city> 
                <state>MD</state>
                <zipcode>90001</zipcode> 
                <country>US</country>
            </org>
   
    + Header
    
            "icSessionId": "EFelWYBP4WmMeO2g9PJs"
            "Content-Type": "application/xml"
            "Accept": "application/xml"
           
+ Response 200 
    
        
## DeleteOrg [/org/<orgid>]

### Use this resource to delete an Informatica Cloud sub-organization if the user that started the Informatica Cloud REST API session has the Admin role and belongs the parent organization [DELETE]

+ Parameters
    + id (required,string, `Org000IL1`) ... Organization ID
+ Request  

    + Header
    
            "icSessionId": "EFelWYBP4WmMeO2g9PJs"
            "Content-Type": "application/xml"
            "Accept": "application/xml"
        
+ Response 200

# Group BundleObject

## bundleObject [/bundleObkject/<id>/?published=value&installed=value]

### Use this resource to request the details for a specific bundle or the details for all bundles published by the organization or installed by the organization and also push a published private bundle to sub-organizations [GET]
To request the details of a bundle, use the bundle ID.
To request the details for all bundles published by the organization, use published as true.
To request the details for all bundles installed by the organization, use installed as true.

+ Parameters
    + id (required,string, `000IL115000000000002`) ... details of a bundle
    + published (required, string, `true`) ... details for all bundles published by the organization
    + installed ( required, sting , `true`) ... details for all bundles installed by the organization

+ Request (application/json)

    + Header
    
            "icSessionId":"EFelWYBP4WmMeO2g9PJs"
            "Content-Type": "application/json"
            "Accept" :"application/json"
            
+ Response 200

        {
          "@type" : "bundleObject",
          "id" : "000IL115000000000002",
          "orgId" : "Org000IL1",
          "name" : "India Contact Validation",
          "description" : "A bundle of mapplets which can be used to validate the India specific contact details like phone number, mobile number, postal code (PIN Code), PAN number,  Passport number etc.
                        The mapplets in this bundle use regular expression to perform the data validation",
          "createTime" : "2015-01-14T18:01:54.000Z",
          "updateTime" : "2015-01-31T15:46:34.000Z",
          "createdBy" : "System",
          "updatedBy" : "nbrisoux@informatica.com",
          "lastVersion" : 1.0,
          "revokeTime" : null,
          "paid" : "false",
          "accessType" : "public",
          "objects" : "Bundle Contents",
          "publishOrgId" : "Org000IL1",
          "publishOrgName" : "Informatica"
          }






        